src/Entity/ComputerUser.php
<?php

namespace App\Entity;

use App\Repository\ComputerUserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ComputerUserRepository::class)]
class ComputerUser
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $Name = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $Surname = null;

    #[ORM\Column(length: 64, nullable: true)]
    private ?string $postalCode = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $City = null;

    #[ORM\Column(length: 1024, nullable: true)]
    private ?string $address = null;

    #[ORM\Column(length: 64, nullable: true)]
    private ?string $phoneNumber = null;

    #[ORM\Column(type: Types::DATETIMETZ_MUTABLE)]
    private ?\DateTimeInterface $creationDate = null;

    #[ORM\Column(type: Types::DATETIMETZ_MUTABLE, nullable: true)]
    private ?\DateTimeInterface $updatedDate = null;

    #[ORM\OneToMany(mappedBy: 'computerUser', targetEntity: Request::class)]
    private Collection $requests;

    public function __construct()
    {
        $this->requests = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->Name;
    }

    public function setName(string $Name): static
    {
        $this->Name = $Name;

        return $this;
    }

    public function getSurname(): ?string
    {
        return $this->Surname;
    }

    public function setSurname(?string $Surname): static
    {
        $this->Surname = $Surname;

        return $this;
    }

    public function getPostalCode(): ?string
    {
        return $this->postalCode;
    }

    public function setPostalCode(?string $postalCode): static
    {
        $this->postalCode = $postalCode;

        return $this;
    }

    public function getCity(): ?string
    {
        return $this->City;
    }

    public function setCity(?string $City): static
    {
        $this->City = $City;

        return $this;
    }

    public function getAddress(): ?string
    {
        return $this->address;
    }

    public function setAddress(?string $address): static
    {
        $this->address = $address;

        return $this;
    }

    public function getPhoneNumber(): ?string
    {
        return $this->phoneNumber;
    }

    public function setPhoneNumber(?string $phoneNumber): static
    {
        $this->phoneNumber = $phoneNumber;

        return $this;
    }

    public function getCreationDate(): ?\DateTimeInterface
    {
        return $this->creationDate;
    }

    public function setCreationDate(\DateTimeInterface $creationDate): static
    {
        $this->creationDate = $creationDate;

        return $this;
    }

    public function getUpdatedDate(): ?\DateTimeInterface
    {
        return $this->updatedDate;
    }

    public function setUpdatedDate(?\DateTimeInterface $updatedDate): static
    {
        $this->updatedDate = $updatedDate;

        return $this;
    }

    /**
     * @return Collection<int, Request>
     */
    public function getRequests(): Collection
    {
        return $this->requests;
    }

    public function addRequest(Request $request): static
    {
        if (!$this->requests->contains($request)) {
            $this->requests->add($request);
            $request->setComputerUser($this);
        }

        return $this;
    }

    public function removeRequest(Request $request): static
    {
        if ($this->requests->removeElement($request)) {
            // set the owning side to null (unless already changed)
            if ($request->getComputerUser() === $this) {
                $request->setComputerUser(null);
            }
        }

        return $this;
    }

    public function __toString(): string
    {
        return "{ 'nom' : '$this->Name', 'id': '$this->id', 'Surname': '$this->Surname', 'address': $this->address', 'City': $this->City', 'phoneNumber': '$this->phoneNumber', 'postalCode': '$this->postalCode'";
    }
}

templates/computerRequests/newComputerUser.html.twig
{% extends "dashboard/userspace.html.twig" %}

{% block page %}
    <div class="bg-white border border-2 rounded-lg shadow relative mx-auto mt-2 w-full sm:w-4/6">
	<div class="flex items-start justify-between p-5 border-b rounded-t">
        	<h3 class="text-xl font-semibold">
            		Créer une nouvelle demande
	        </h3>
	</div>
	<div class="p-1 sm:p-6 space-y-6">
	
	{{ form_start(computerUserForm) }}
		<div class="grid grid-cols-4">
	        <div class="p-1 col-span-4 md:col-span-2 ">
			{{ form_row(
				computerUserForm.Name,
				{
					'label': 'Nom',
					'label_attr' : { 'class': 'text-sm font-medium text-gray-900 block mb-2' }
					,'attr' : { 'class' : 'shadow-sm bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg focus:ring-fuchsia-600 focus:border-fuchsia-600 block w-full p-2.5'  }
				})
			}}
			</div>
	        <div class="p-1 col-span-4 md:col-span-2">
			{{ form_row(
				computerUserForm.Surname,
				{
					'label': 'Prénom',
					'label_attr' : { 'class': 'text-sm font-medium text-gray-900 block mb-2' }
					,'attr' : { 'class' : 'shadow-sm bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg focus:ring-fuchsia-600 focus:border-fuchsia-600 block w-full p-2.5'  }
				})
			}}
			</div>
			<div class="p-1 col-span-4 md:col-span-1">
				{{ form_row(
					computerUserForm.phoneNumber,
					{
						'label': 'Numéro de téléphone',
						'label_attr' : { 'class': 'text-sm font-medium text-gray-900 block mb-2' }
						,'attr' : { 'class' : 'shadow-sm bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg focus:ring-fuchsia-600 focus:border-fuchsia-600 block w-full p-2.5'  }
					})
				}}
			</div>
			<div class="p-1 col-span-0 md:col-span-3">
			</div>
	        <div class="p-1 col-span-4 md:col-span-1">
			{{ form_row(
				computerUserForm.postalCode,
				{
					'label': 'Code postal',
					'label_attr' : { 'class': 'text-sm font-medium text-gray-900 block mb-2' }
					,'attr' : { 'class' : 'shadow-sm bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg focus:ring-fuchsia-600 focus:border-fuchsia-600 block w-full p-2.5'  }
				})
			}}
			</div>
			<div class="p-1 col-span-4 md:col-span-3">
			{{ form_row(
				computerUserForm.City,
				{
					'label': 'Ville',
					'label_attr' : { 'class': 'text-sm font-medium text-gray-900 block mb-2' }
					,'attr' : { 'class' : 'shadow-sm bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg focus:ring-fuchsia-600 focus:border-fuchsia-600 block w-full p-2.5'  }
				})
			}}
			</div>
	        <div class="p-1 col-span-4">
			{{ form_row(
				computerUserForm.address,
				{
					'label': 'Adresse',
					'label_attr' : { 'class': 'text-sm font-medium text-gray-900 block mb-2' }
					,'attr' : { 'class' : 'shadow-sm bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg focus:ring-fuchsia-600 focus:border-fuchsia-600 block w-full p-2.5'  }
				})
			}}
			</div>
			<div class="p-1 col-span-4">
			{{ form_row(computerUserForm.computerType, {
				label: 'Type de PC',
				label_attr : { 'class': 'text-sm font-medium text-gray-900 block mb-2' }
				,attr : { 'class' : 'shadow-sm bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg focus:ring-fuchsia-600 focus:border-fuchsia-600 block w-full p-2.5'  }

			}) }}
			</div>
		</div>
		<div class="p-6 border-t border-gray-200 rounded-b">
		        <button class="text-white bg-fuchsia-600 hover:bg-fuchsia-700 focus:ring-4 focus:ring-fuchsia-200 font-medium rounded-lg text-sm px-5 py-2.5 text-center" type="submit">Demander</button>
		</div>
	{{ form_end(computerUserForm) }}

	</div>
    </div>
{% endblock %}

templates/computerRequests/requestAccepted.html.twig
{% extends "dashboard/userspace.html.twig" %}

{% block page %}
    <div class="bg-white border border-2 rounded-lg shadow relative mx-auto mt-2 w-full sm:w-4/6">
        <h1 class="bg-green-400 border border-2 text-center p-2">Bravo, la demande n° {{ requestId }} a été prise en compte !</h1>

        <div class="p-6 border-t border-gray-200 rounded-b text-center">
        <a class="text-white bg-fuchsia-600 hover:bg-fuchsia-700 focus:ring-4 focus:ring-fuchsia-200 font-medium rounded-lg text-sm px-5 py-2.5 text-center" href="{{ path('app_user_start_new_request') }}">Créer une nouvelle demande.</a>
        </div>
    </div>
{% endblock %}

templates/computerRequests/showUserRequests.html.twig
{% extends "dashboard/userspace.html.twig" %}

{% block page %}
    <div class="flex flex-col">
        <div class="-m-1.5 overflow-x-auto">
            <div class="p-1.5 min-w-full inline-block align-middle">
                <div>
                    <button><a href="{{ path('app_user_start_new_request') }}">Créer une nouvelle demande.</a></button>
                </div>
                <div class="border rounded-lg divide-y divide-gray-200 dark:border-gray-700 dark:divide-gray-700">
                    <div class="overflow-hidden">
                        <table class="min-w-full divide-y divide-gray-200 dark:divide-gray-700">
                            <thead class="bg-fuchsia-50 dark:bg-fuchsia-700">
                            <tr>
                                <th scope="col" class="px-6 py-3 text-start text-xs font-medium text-gray-500 uppercase">N°</th>
                                <th scope="col" class="px-6 py-3 text-start text-xs font-medium text-gray-500 uppercase">Type</th>
                                <th scope="col" class="px-6 py-3 text-start text-xs font-medium text-gray-500 uppercase">Bénéficiaire</th>
                                <th scope="col" class="px-6 py-3 text-start text-xs font-medium text-gray-500 uppercase">Date de dernier contact</th>
                                <th scope="col" class="px-6 py-3 text-start text-xs font-medium text-gray-500 uppercase">Date de la demande</th>
                                <th scope="col" class="px-6 py-3 text-start text-xs font-medium text-gray-500 uppercase">Statut</th>
                            </tr></thead>
                            <tbody class="divide-y divide-gray-200 dark:divide-gray-700">
                                {% for request in requests %}
                                <tr>
                                    <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-800 dark:text-gray-200">{{ request.id }}</td>
                                    <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-800 dark:text-gray-200">{{ request.computerType.label }}</td>
                                    <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-800 dark:text-gray-200">{{ request.computerUser.surname ~ " " ~ request.computerUser.name }}</td>
                                    <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-800 dark:text-gray-200">{{ request.lastContactDate | default('Aucune') }}</td>
                                    <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-800 dark:text-gray-200">{{ request.requestDate | date('d-m-Y') }}</td>
                                    <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-800 dark:text-gray-200">{{ request.status.label }}</td>
                                </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                <div>
            <div>
        <div>
    </div>
{% endblock %}